package com.creativemd.itemphysic;

import static com.creativemd.itemphysic.ItemPhysic.MODID;
import static com.creativemd.itemphysic.ItemPhysic.NAME;
import static com.creativemd.itemphysic.ItemPhysic.VERSION;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;

import com.creativemd.itemphysic.config.ItemPhysicConfig;
import com.creativemd.itemphysic.list.BurnListRegistry;
import com.creativemd.itemphysic.list.ExplosionListRegistry;
import com.creativemd.itemphysic.list.FloatListRegistry;
import com.creativemd.itemphysic.list.IgnitingListRegistry;
import com.creativemd.itemphysic.list.SulfuricAcidListRegistry;
import com.creativemd.itemphysic.list.UndestroyableListRegistry;
import com.creativemd.itemphysic.packet.PacketDispatcher;
import com.creativemd.itemphysic.physics.ClientPhysic;
import com.creativemd.itemphysic.proxy.CommonProxy;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.gameevent.TickEvent;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@Mod(
    modid = MODID,
    version = VERSION,
    name = NAME,
    guiFactory = "com.creativemd.itemphysic.config.ItemPhysicGuiFactory")
public class ItemPhysic {

    public static final String MODID = "itemphysic";
    public static final String NAME = "ItemPhysic";
    public static final String VERSION = "1.2.8" + " kotmatross edition";
    public static final String CLIENTPROXY = "com.creativemd.itemphysic.proxy.ClientProxy";
    public static final String SERVERPROXY = "com.creativemd.itemphysic.proxy.CommonProxy";
    public static final String VERSION2 = "1.2.8";

    @Mod.Instance(MODID)
    public static ItemPhysic instance;

    @SidedProxy(clientSide = CLIENTPROXY, serverSide = SERVERPROXY)
    public static CommonProxy proxy;

    public static Configuration config;

    protected static void syncConfig() {
        ItemPhysicConfig.loadGeneralConfig(config);
        ItemPhysicConfig.loadBurnListConfig(config);
        ItemPhysicConfig.loadFloatListConfig(config);
        ItemPhysicConfig.loadExplosionListConfig(config);
        ItemPhysicConfig.loadUndestroyableListConfig(config);
        ItemPhysicConfig.loadSulfuricAcidListConfig(config);
        ItemPhysicConfig.loadIgnitingItemsListConfig(config);

        if (config.hasChanged()) config.save();
    }

    @Mod.EventHandler
    public static void preInit(FMLPreInitializationEvent event) {
        config = new Configuration(event.getSuggestedConfigurationFile());
        syncConfig();

        PacketDispatcher.registerPackets();

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = EnumChatFormatting.RED + NAME;
        event.getModMetadata().version = EnumChatFormatting.GRAY + "" + EnumChatFormatting.BOLD + VERSION2;
        event.getModMetadata().credits = EnumChatFormatting.GOLD + "CreativeMD";

        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(EnumChatFormatting.GOLD + "CreativeMD");
        event.getModMetadata().authorList.add(EnumChatFormatting.RED + "HRudyPlayZ");
        event.getModMetadata().authorList.add(EnumChatFormatting.AQUA + "Kotmatross");

        event.getModMetadata().url = "https://github.com/kotmatross28729/ItemPhysic-Legacy-Unofficial";
        event.getModMetadata().description = EnumChatFormatting.GRAY
            + "A minecraft mod that adds physics to thrown items.";
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.registerEvents();
        proxy.init(this);

        if (FMLCommonHandler.instance()
            .getSide()
            .isClient()) {
            MinecraftForge.EVENT_BUS.register(new EventHandlerClient());
            FMLCommonHandler.instance()
                .bus()
                .register(new EventHandlerClient());
        }

        MinecraftForge.EVENT_BUS.register(new EventHandler());
        FMLCommonHandler.instance()
            .bus()
            .register(new EventHandler());
    }

    @Mod.EventHandler
    @SideOnly(Side.CLIENT)
    public void onRender(TickEvent.RenderTickEvent evt) {
        ClientPhysic.tick = System.nanoTime();
    }

    public static boolean isHBMLoaded = false;

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        if (Loader.isModLoaded("hbm")) {
            isHBMLoaded = true;
        }
        BurnListRegistry.registerDefaults();
        FloatListRegistry.registerDefaults();
        ExplosionListRegistry.registerDefaults();
        UndestroyableListRegistry.registerDefaults();
        if (isHBMLoaded) SulfuricAcidListRegistry.registerDefaults();
        IgnitingListRegistry.registerDefaults();
    }

}
